### PR TITLE
implement aspect ratio option

### PR DESCRIPTION
**Pull request by Ishan09811**
Thanks to @t895 though he didn't helped in this implementation but I got the surface updating for aspect ratio Idea from his work so thanks to t895

### CODE REVIEW

**Comment by ghost** [comment]
It's broken on dual screen mode 



The top screen on the default 16:9 ratio is squashed

**Comment by Ishan09811** [comment]
> It's broken on dual screen mode
> 
> 
> 
> The top screen on the default 16:9 ratio is squashed

it is working as I expected because the position of the first screen and second screen is decided in native so I need to research more about it to set the position of both screen but it will work fine with single screen.

**Comment by ghost** [comment]
> > It's broken on dual screen mode
> > 
> > The top screen on the default 16:9 ratio is squashed
> 
> it is working as I expected because the position of the first screen and second screen is decided in native so I need to research more about it to set the position of both screen but it will work fine with single screen.


Than it should be off by default since most users play with 2 screens

**Comment by ghost** [comment]
Now, the option doesn't seem to work

**Comment by runsrr** [comment]
Can this be added to the windows version please?

**Comment by ghost** [comment]
@Gamer64ytb Can you add this to QT?

**Comment by Gamer64ytb** [comment]
Ill try to do a C++ implementation, or just to add a stretch to window option

**Pull request closed without merging**
