### PR TITLE
Implement game shortcut option 

### PR DESCRIPTION
**Pull request by Ishan09811**
credits: @t895

### CODE REVIEW

**Comment by kleidis** [comment]
Couple of bugs:

# 1. If a game crashes, it goes to the citra ui, and you can not boot it anymore. You get a `non bookable game found` error 

# 2.You can create multiple shortcuts of the same game

**Comment by kleidis** [comment]
Couple of bugs:

# 1. If a game crashes, it goes to the citra ui, and you can not boot it anymore. You get a `non bookable game found` error 

# 2.You can create multiple shortcuts of the same game

**Comment by OpenSauce04** [comment]
The commits in this PR do not attribute the original author, so I would advise amending the commit message of cc926de to add a coauthor before merging.

**Comment by kleidis** [comment]
@Ishan09811 You might want to consider finishing this because it was a heavily requested feature as far 

Make another PR with proper crediting as well

**Comment by kleidis** [comment]
This should be closed at this point

**Comment by Ishan09811** [comment]
This is no more mergeable as the master source is rewriten

**Pull request closed without merging**
