### PR TITLE
Drop the SDL Frontend

### PR DESCRIPTION
**Pull request by ghost**
Your favorite contributor hi
Since you were feeling too lazy to cherry-pick this one, I did it for you :)
I expect 99% ownership of mandarine3DS now and a 20$ tip to my cash app

### CODE REVIEW

**Comment by hansmalcolm** [comment]
> Your favorite contributor hi Since you were feeling too lazy to cherry-pick this one, I did it for you :) I expect 99% ownership of mandarine3DS now and a 20$ tip to my cash app

No

**Comment by kleidis** [comment]
> > Your favorite contributor hi Since you were feeling too lazy to cherry-pick this one, I did it for you :) I expect 99% ownership of mandarine3DS now and a 20$ tip to my cash app
> 
> No

Po

**Comment by ghost** [comment]
> > Your favorite contributor hi Since you were feeling too lazy to cherry-pick this one, I did it for you :) I expect 99% ownership of mandarine3DS now and a 20$ tip to my cash app
> 
> No

Avarage Mandarine Fan

**Comment by hansmalcolm** [comment]
> > > Your favorite contributor hi Since you were feeling too lazy to cherry-pick this one, I did it for you :) I expect 99% ownership of mandarine3DS now and a 20$ tip to my cash app
> > 
> > 
> > No
> 
> Avarage Mandarine Fan

You are not mandarine fan

**Comment by ghost** [comment]
On second thought, you might wanna reconsider this since it apparently breaks "automated setups"

Waiting for more details , Hopefully, he replies

**Comment by hansmalcolm** [comment]
> 
> 
> On second thought, you might wanna reconsider this since it apparently breaks "automated setups"
> 
> Waiting for more details , Hopefully, he replies

This will never hapening in mandarine

**Comment by ghost** [comment]
> > 
> > 
> > On second thought, you might wanna reconsider this since it apparently breaks "automated setups"
> > 
> > Waiting for more details , Hopefully, he replies
> 
> This will never hapening in mandarine

If you become a bad boy, i will tell @Gamer64ytb to ban you off the repo and discord 😕

**Comment by hansmalcolm** [comment]
> > > 
> > > On second thought, you might wanna reconsider this since it apparently breaks "automated setups"
> > > Waiting for more details , Hopefully, he replies
> > 
> > 
> > This will never hapening in mandarine
> 
> If you become a bad boy, i will tell @Gamer64ytb to ban you off the repo and discord 😕

You will be reported to discord, don't worry :), and i will tell that you ban from the repo too
I am tired of you

**Comment by hansmalcolm** [comment]
@kleidis Just let mandarine alone

**Review by Gamer64ytb — APPROVED** [review]
Tested on my PC and all seems to be fine. I'll send this build to my testers and if no issues as well, I'll merge it

**Pull request merged**
